# Generated by Django 5.2.7 on 2025-10-23 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado')], default='activo', max_length=30)),
                ('nota_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='estudiante',
            field=models.ManyToManyField(related_name='cursos', through='academico.Inscripciones', to='academico.estudiante'),
        ),
    ]
